import type { CoreAnalysisMode, ModeUsageRole } from "../types";

export type DecodingMappingType = "exact" | "partial" | "form-layer" | "missing";
export type DecodingCategoryKind = "concept" | "analogy" | "strategy" | "speech-act" | "guardrail";
export type DecodingBoundarySensitivity = "standard" | "context-heavy" | "contested";

export interface DecodingAntisemitismCrosswalkItem {
  decodingId: string;
  decodingCategory: string;
  part: string;
  chapter: string;
  categoryKind: DecodingCategoryKind;
  mappingType: DecodingMappingType;
  textLensTaxonomyItemIds: string[];
  sourceRoleByMode: Partial<Record<CoreAnalysisMode, ModeUsageRole>>;
  boundarySensitivity: DecodingBoundarySensitivity;
  note: string;
}

const DEFAULT_SOURCE_ROLE_BY_MODE: Partial<Record<CoreAnalysisMode, ModeUsageRole>> = {
  decoding_antisemitism: "primary",
  general: "supporting",
  healthcare: "advisory",
  academic: "advisory",
  legal_profession: "advisory",
  bccsa: "advisory",
  press_code: "advisory",
};

export const decodingAntisemitismCrosswalk: DecodingAntisemitismCrosswalkItem[] = [
  {
    decodingId: "DA-OTHER-FOREIGN",
    decodingCategory: "The Other / Foreign",
    part: "Classic Antisemitism",
    chapter: "2",
    categoryKind: "concept",
    mappingType: "partial",
    textLensTaxonomyItemIds: ["L1-HOSTILITY", "L2-PEOPLEHOOD", "L2-RACISM-RACIAL"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "context-heavy",
    note: "Use for constructions of Jewish or Israeli foreignness, non-belonging, or lack of historical connection. Preserve the distinction between national comparison and exclusionary othering.",
  },
  {
    decodingId: "DA-EVIL-DEVIL",
    decodingCategory: "Evil / The Devil",
    part: "Classic Antisemitism",
    chapter: "3",
    categoryKind: "concept",
    mappingType: "partial",
    textLensTaxonomyItemIds: ["L1-HOSTILITY", "L2-VEHICLE-OLD-TROPES"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "context-heavy",
    note: "Use where evil is attributed as a constitutive quality of Jews, Israel, Israelis, Zionists or Zionism, not merely as criticism of a particular act.",
  },
  {
    decodingId: "DA-BLOOD-LIBEL",
    decodingCategory: "Blood Libel / Child Murder",
    part: "Classic Antisemitism",
    chapter: "4",
    categoryKind: "concept",
    mappingType: "exact",
    textLensTaxonomyItemIds: ["L1-BLOOD"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "standard",
    note: "Use for false, generalised, intentionalising, ritualising, or routinising claims of child murder by Jews, Israel, Israelis, Zionists or Zionism.",
  },
  {
    decodingId: "DA-DEHUMANISATION",
    decodingCategory: "Repulsiveness and Dehumanisation",
    part: "Classic Antisemitism",
    chapter: "5",
    categoryKind: "concept",
    mappingType: "exact",
    textLensTaxonomyItemIds: ["L1-DEHUMAN"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "standard",
    note: "Use for animalisation, pest-control metaphors, disease imagery, denial of human status, racial physiognomy, or essentialised Jewish mindset claims.",
  },
  {
    decodingId: "DA-IMMORALITY",
    decodingCategory: "Immorality",
    part: "Classic Antisemitism",
    chapter: "6",
    categoryKind: "concept",
    mappingType: "partial",
    textLensTaxonomyItemIds: ["L1-HOSTILITY", "L2-VEHICLE-OLD-TROPES"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "context-heavy",
    note: "Use for claims that Jews, Israel, Israelis or Zionism lack ordinary moral feeling or are released by Jewish teaching from normal moral constraints.",
  },
  {
    decodingId: "DA-LIE-DECEIT",
    decodingCategory: "Lie and Deceit",
    part: "Classic Antisemitism",
    chapter: "7",
    categoryKind: "concept",
    mappingType: "partial",
    textLensTaxonomyItemIds: ["L1-CONSPIRACY", "L3-6-4"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "context-heavy",
    note: "Use only for essentialising claims of Jewish, Israeli, Zionist or Zionist-institutional mendacity; do not apply to concrete, evidence-based disputes over a specific falsehood.",
  },
  {
    decodingId: "DA-VENGEFULNESS",
    decodingCategory: "Vengefulness",
    part: "Classic Antisemitism",
    chapter: "8",
    categoryKind: "concept",
    mappingType: "partial",
    textLensTaxonomyItemIds: ["L1-HOSTILITY", "L3-3-3"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "context-heavy",
    note: "Use for essentialising claims that revenge, bloodthirstiness, sadism, or disproportionate retaliation are features of Judaism, Jews, Israelis or Zionism.",
  },
  {
    decodingId: "DA-DISLOYALTY",
    decodingCategory: "Disloyalty / Jewish Loyalty",
    part: "Classic Antisemitism",
    chapter: "9",
    categoryKind: "concept",
    mappingType: "exact",
    textLensTaxonomyItemIds: ["L1-LOYALTY"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "standard",
    note: "Use for claims that Jews are disloyal to their home country or loyal first/exclusively to Israel, Jews worldwide, or non-local Jewish interests.",
  },
  {
    decodingId: "DA-BLAME-FOR-ANTISEMITISM",
    decodingCategory: "Blame for Antisemitism",
    part: "Classic Antisemitism",
    chapter: "10",
    categoryKind: "strategy",
    mappingType: "partial",
    textLensTaxonomyItemIds: ["L2-VICTIM-MINIMISE", "L3-6-5", "L3-6-6"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "context-heavy",
    note: "Use when antisemitism is characterised as self-inflicted, caused, justified, or legitimised by Jewish or Israeli behaviour.",
  },
  {
    decodingId: "DA-GREED-EXPLOITATION-CAPITALISM",
    decodingCategory: "Greed, Exploitation and Identification with Capitalism",
    part: "Concepts of Power",
    chapter: "11",
    categoryKind: "concept",
    mappingType: "partial",
    textLensTaxonomyItemIds: ["L1-POWER", "L1-CONSPIRACY"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "context-heavy",
    note: "Use for generalised or essentialised greed, exploitation, parasitism, or capitalism-as-Jewish claims. Treat accusations against lesser-known individuals cautiously unless other tropes are present.",
  },
  {
    decodingId: "DA-POWER",
    decodingCategory: "Power",
    part: "Concepts of Power",
    chapter: "12",
    categoryKind: "concept",
    mappingType: "exact",
    textLensTaxonomyItemIds: ["L1-POWER"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "standard",
    note: "Use for insinuations of overwhelming power, omnipotence, or society, politics or media being submissive to Jews, Israel, Israelis or Zionists.",
  },
  {
    decodingId: "DA-CONSPIRACY",
    decodingCategory: "Conspiracy Theories",
    part: "Concepts of Power",
    chapter: "13",
    categoryKind: "concept",
    mappingType: "exact",
    textLensTaxonomyItemIds: ["L1-CONSPIRACY", "L1-POWER"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "standard",
    note: "Use for hidden-control narratives or explanations of events that assign a concealed nefarious Jewish, Israeli or Zionist role. Structural conspiracy without a Jewish referent is not antisemitic per se.",
  },
  {
    decodingId: "DA-DISINTEGRATION",
    decodingCategory: "Disintegration",
    part: "Concepts of Power",
    chapter: "14",
    categoryKind: "concept",
    mappingType: "partial",
    textLensTaxonomyItemIds: ["L1-CONSPIRACY", "L1-HOSTILITY"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "context-heavy",
    note: "Use for claims that Jews, Israel or recognised Jewish figures destroy cohesion, democracy, economy, national order, religion, family or desirable social units.",
  },
  {
    decodingId: "DA-SELF-VICTIMISATION",
    decodingCategory: "Self-victimisation",
    part: "Concepts of Power",
    chapter: "15",
    categoryKind: "strategy",
    mappingType: "partial",
    textLensTaxonomyItemIds: ["L3-6-5", "L3-6-6"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "context-heavy",
    note: "Use for portrayals of public figures or groups as victimised by Jews, Israel, Zionism or antisemitism prevention. Do not apply to documented incidents of victimhood.",
  },
  {
    decodingId: "DA-HOLOCAUST-DISTORTION-DENIAL",
    decodingCategory: "Holocaust Distortion and Denial",
    part: "Secondary Antisemitism",
    chapter: "18",
    categoryKind: "strategy",
    mappingType: "exact",
    textLensTaxonomyItemIds: ["L1-HOLOCAUST", "L2-VICTIM-MINIMISE"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "standard",
    note: "Use for denial of the Holocaust, rejection of central extermination features, minimisation, blame-shifting, or relativising equivalences that erase essential characteristics.",
  },
  {
    decodingId: "DA-RELATIVISATION-DENIAL-ANTISEMITISM",
    decodingCategory: "Relativisation and Denial of Antisemitism",
    part: "Secondary Antisemitism",
    chapter: "19",
    categoryKind: "strategy",
    mappingType: "partial",
    textLensTaxonomyItemIds: ["L2-VICTIM-MINIMISE", "L3-6-2", "L3-6-3"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "context-heavy",
    note: "Use for minimising antisemitism, denying it in contexts where it is broadly recognisable, or reclassifying antisemitism as mere criticism without engaging the triggering content.",
  },
  {
    decodingId: "DA-INSTRUMENTALISATION",
    decodingCategory: "Instrumentalisation of Antisemitism and the Holocaust",
    part: "Secondary Antisemitism",
    chapter: "20",
    categoryKind: "strategy",
    mappingType: "partial",
    textLensTaxonomyItemIds: ["L3-6-3", "L3-6-4", "L3-6-6"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "context-heavy",
    note: "Use for claims that Jews, Israel or allies exploit antisemitism or the Holocaust as a hidden agenda or mere rhetorical tool. Do not suppress legitimate criticism of false accusations.",
  },
  {
    decodingId: "DA-NAZI-COLLABORATION",
    decodingCategory: "Nazi-Jewish Collaboration",
    part: "Secondary Antisemitism",
    chapter: "21",
    categoryKind: "strategy",
    mappingType: "partial",
    textLensTaxonomyItemIds: ["L1-HOLOCAUST", "L1-CONSPIRACY"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "standard",
    note: "Use for claims that the Holocaust was organised, supported, instigated, traded, or instrumentally tolerated by Jews, Zionists or Jewish elites.",
  },
  {
    decodingId: "DA-TABOO-CRITICISM",
    decodingCategory: "Taboo of Criticism",
    part: "Secondary Antisemitism",
    chapter: "23",
    categoryKind: "strategy",
    mappingType: "partial",
    textLensTaxonomyItemIds: ["L3-6-2", "L3-6-3", "L3-6-6", "L1-POWER"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "context-heavy",
    note: "Use where the text claims systematic suppression of criticism by Jews, Israel, Zionists or allies; do not apply to ordinary disagreement about speech norms or specific laws.",
  },
  {
    decodingId: "DA-NOT-LEARNED",
    decodingCategory: "Jews Have Not Learned From the Past",
    part: "Secondary Antisemitism",
    chapter: "24",
    categoryKind: "strategy",
    mappingType: "partial",
    textLensTaxonomyItemIds: ["L2-VICTIM-MINIMISE", "L3-7-4"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "context-heavy",
    note: "Use where Jewish suffering is invoked as a lesson Jews allegedly failed to learn, often converting memory of persecution into a charge against Jews or Israel.",
  },
  {
    decodingId: "DA-COLLECTIVE-RESPONSIBILITY-ISRAEL",
    decodingCategory: "Holding Jews Collectively Responsible for Israel's Actions",
    part: "Further Post-Holocaust Categories",
    chapter: "25",
    categoryKind: "concept",
    mappingType: "exact",
    textLensTaxonomyItemIds: ["L1-GUILT", "L2-COLLECTIVE-RESP", "L3-4-1"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "standard",
    note: "Use for explicit or implicit treatment of Jews and Israelis as one bloc, including blame, advice, punishment, or rhetorical questions directed at non-Israeli Jews.",
  },
  {
    decodingId: "DA-JEWISH-PRIVILEGE",
    decodingCategory: "Jewish Privilege and the Free Pass",
    part: "Further Post-Holocaust Categories",
    chapter: "26",
    categoryKind: "concept",
    mappingType: "partial",
    textLensTaxonomyItemIds: ["L2-UNIQUE-ILLEGIT", "L3-6-6"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "context-heavy",
    note: "Use for claims that Jews or Israel are untouchable, immune, specially protected, chosen as a master race, or given impunity because of the Shoah or hidden pressure.",
  },
  {
    decodingId: "DA-NAZI-AFFIRMATION",
    decodingCategory: "Affirmation of Nazis, Hitler and the Holocaust",
    part: "Further Post-Holocaust Categories",
    chapter: "27",
    categoryKind: "strategy",
    mappingType: "partial",
    textLensTaxonomyItemIds: ["L1-NAZI-DIRECT", "L1-HOLOCAUST"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "standard",
    note: "Use for positive evaluation of Hitler, Nazism, Nazi institutions, Holocaust continuation, perpetrator rehabilitation, or humorous trivialisation that endorses perpetrators.",
  },
  {
    decodingId: "DA-NAZI-FASCISM-ANALOGY",
    decodingCategory: "Nazi Analogy / Fascism Analogies",
    part: "Israel-Related Antisemitism",
    chapter: "28",
    categoryKind: "analogy",
    mappingType: "exact",
    textLensTaxonomyItemIds: ["L1-NAZI-DIRECT", "L2-NAZI-INVERSION", "L3-4-4"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "contested",
    note: "Use for comparisons of Jews, Israel, Israelis or Zionism with Nazi Germany, fascist regimes, ideologies or movements. Fascism claims against specific parties or individuals require narrower handling.",
  },
  {
    decodingId: "DA-APARTHEID-RACIST-STATE",
    decodingCategory: "Apartheid Analogy / Racist State",
    part: "Israel-Related Antisemitism",
    chapter: "29",
    categoryKind: "analogy",
    mappingType: "partial",
    textLensTaxonomyItemIds: ["L2-RACISM-RACIAL", "L2-UNSUPPORTED-FRAMING", "L3-4-4"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "contested",
    note: "Use for generalised analogy between Israel as a whole and apartheid or racial statehood. Treat time-, place-, policy- or West Bank-limited claims case by case.",
  },
  {
    decodingId: "DA-COLONIALISM-ANALOGIES",
    decodingCategory: "Colonialism Analogies",
    part: "Israel-Related Antisemitism",
    chapter: "30",
    categoryKind: "analogy",
    mappingType: "partial",
    textLensTaxonomyItemIds: ["L2-RACISM-RACIAL", "L2-EXCEPT-DELEGIT", "L3-4-4"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "contested",
    note: "Use for analogies between Israel as a whole and past colonial states or colonial policies. Do not apply to settlement-policy claims limited to the West Bank or Golan Heights without whole-state inculpation.",
  },
  {
    decodingId: "DA-TERRORIST-STATE",
    decodingCategory: "Terrorist State",
    part: "Israel-Related Antisemitism",
    chapter: "31",
    categoryKind: "analogy",
    mappingType: "partial",
    textLensTaxonomyItemIds: ["L2-UNSUPPORTED-FRAMING", "L2-EXCEPT-DELEGIT"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "context-heavy",
    note: "Use for claims that Israel, Zionism, Israelis or Jews are terroristic entities in their entirety, or that specific founding-era incidents define Israel or Zionism as such.",
  },
  {
    decodingId: "DA-GENOCIDE",
    decodingCategory: "Genocide",
    part: "Israel-Related Antisemitism",
    chapter: "32",
    categoryKind: "analogy",
    mappingType: "partial",
    textLensTaxonomyItemIds: ["L2-UNSUPPORTED-FRAMING", "L2-NAZI-INVERSION", "L3-4-4"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "contested",
    note: "Use for generalised accusations that Israel has committed, is committing, or plans genocide, or for equivalences to past genocides. Genuine investigation or narrower actor-limited claims require restraint.",
  },
  {
    decodingId: "DA-DOUBLE-STANDARDS",
    decodingCategory: "Double Standards",
    part: "Israel-Related Antisemitism",
    chapter: "33",
    categoryKind: "strategy",
    mappingType: "exact",
    textLensTaxonomyItemIds: ["L2-UNIQUE-ILLEGIT", "L2-DOUBLE-CONFLICTS"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "contested",
    note: "Use cautiously because standalone comments often lack enough comparator evidence. Treat as potential mode of analysis, not automatic proof.",
  },
  {
    decodingId: "DA-DENIAL-ISRAEL-RIGHT-TO-EXIST",
    decodingCategory: "Denial of Israel's Right to Exist",
    part: "Israel-Related Antisemitism",
    chapter: "34",
    categoryKind: "concept",
    mappingType: "exact",
    textLensTaxonomyItemIds: ["L2-PEOPLEHOOD", "L2-EXCEPT-DELEGIT", "L2-ELIMINATION"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "contested",
    note: "Use for denial of Israeli statehood in recognised borders, denial of a Jewish state as such, denial of Jewish connection to the territory, or singling out Zionism as uniquely illegitimate nationalism.",
  },
  {
    decodingId: "DA-BDS-BOYCOTT",
    decodingCategory: "Calls for Boycott of Israel and Support for BDS",
    part: "Israel-Related Antisemitism",
    chapter: "35",
    categoryKind: "strategy",
    mappingType: "partial",
    textLensTaxonomyItemIds: ["L0-BOYCOTT-BDS", "L2-EXCEPT-DELEGIT"],
    sourceRoleByMode: {
      ...DEFAULT_SOURCE_ROLE_BY_MODE,
      general: "advisory",
      healthcare: "guardrail",
      academic: "guardrail",
      legal_profession: "guardrail",
      bccsa: "guardrail",
      press_code: "guardrail",
    },
    boundarySensitivity: "contested",
    note: "Use as a source-specific category in Decoding mode. In other modes, keep BDS support protected unless added aggravating features are present.",
  },
  {
    decodingId: "DA-ISRAEL-SOLE-GUILT",
    decodingCategory: "Israel's Sole Guilt in the Conflict",
    part: "Israel-Related Antisemitism",
    chapter: "36",
    categoryKind: "strategy",
    mappingType: "partial",
    textLensTaxonomyItemIds: ["L2-DOUBLE-CONFLICTS", "L3-3-2", "L3-3-4"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "context-heavy",
    note: "Use for black-and-white portrayals that deny any non-Israeli agency or responsibility. Single-event claims require close contextual judgement.",
  },
  {
    decodingId: "DA-AGGRESSIVE-SPEECH-ACTS",
    decodingCategory: "Insults, Threats, Curses, Death Wishes, and Calls for Violence",
    part: "Aggressive Speech Acts",
    chapter: "37-42",
    categoryKind: "speech-act",
    mappingType: "form-layer",
    textLensTaxonomyItemIds: ["L1-HOSTILITY", "L2-ELIMINATION"],
    sourceRoleByMode: DEFAULT_SOURCE_ROLE_BY_MODE,
    boundarySensitivity: "standard",
    note: "Use as a form layer: identify the speech act separately from the antisemitic concept it carries. Threats and calls for violence may be antisemitic even without an explicitly named stereotype if the target identity is clear.",
  },
];

export const decodingCrosswalkByTextLensId = decodingAntisemitismCrosswalk.reduce(
  (acc, item) => {
    for (const taxonomyItemId of item.textLensTaxonomyItemIds) {
      const existing = acc.get(taxonomyItemId) || [];
      existing.push(item);
      acc.set(taxonomyItemId, existing);
    }
    return acc;
  },
  new Map<string, DecodingAntisemitismCrosswalkItem[]>()
);

export const decodingMappedTaxonomyItemIds = new Set(
  decodingAntisemitismCrosswalk.flatMap((item) => item.textLensTaxonomyItemIds)
);
